### ISSUE TITLE
[BE] AWS 설정

### ISSUE THREAD

**Issue by dohyeon-han** [softeerbootcamp-2nd/H8-YoungCha#30]
## 작업 내용
- EC2 설정
- 정적 파일 전달

## 할 일
- [x] VPC 생성
- [x] public subnet 설정
  - [x] Java 11 설치
  - [x] Docker 설치
- [x] private subnet 설정
  - [x] MySQL 설치
- [x] S3 bucket 생성
- [x] route53과 S3 연동

## 기타
외부에서 private subnet에 접근할 수 없도록 한다.
https와 cloudfront는 후순위이기 때문에 추후에 연동

**Comment by csct3434** [comment]
- 도메인 설정 완료 : S3 - 루트 도메인, EC2 - 서브 도메인 구성
- Cloudfront, Application Load Balancer, HTTPS 설정
- Nginx 설정
